### ISSUE TITLE
Add sort icon in filter view

### ISSUE THREAD

**Issue by bikramkawan** [Caleydo/mothertable#112]
Add sort icon i.e. asc and dsc in the filter view. In this, we can see the current sort criteria and select sorting criteria from filter view also.

**Comment by mijar** [comment]
@bikramkawan I guess what @mstreit meant by small icon indicating sort direction was this icon in columns, for example in LineUp:
![sorticon](https://cloud.githubusercontent.com/assets/7511570/23171031/a223e202-f851-11e6-8bee-c9a63df35983.PNG)
So in our case, it is in the Table View, not in Filter View. 
Marc am I right or not?

**Comment by mstreit** [comment]
yes, exactly!

**Comment by mstreit** [comment]
No, the point here is that when the user changes the sorting in the table view, it will become the primary sort criteria. We thought about adding ASC/DECS button in the filter view as well so that the user can decide what the sorting should be for each column independently of the primary sorting criteria.

**Comment by mijar** [comment]
Now I am getting the motivation, thank you for clearing this up...

**Comment by bikramkawan** [comment]
![image](https://cloud.githubusercontent.com/assets/12292333/23257570/c0eb534a-f9c4-11e6-92ac-519ee34d4616.png)

**Comment by bikramkawan** [comment]
![feb-26-2017 12-33-13 pm](https://cloud.githubusercontent.com/assets/12292333/23339312/edbc3792-fc1f-11e6-8c4c-8617feee290b.gif)
