### ISSUE TITLE
Handle missing data values in data subsets

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#117]
In this TCGA data example not each gene has a value in the different matrices.

![image](https://cloud.githubusercontent.com/assets/4129755/23173383/47a10e60-f859-11e6-82d5-de44e7d39296.png)

**Comment by thinkh** [comment]
## Problem

At the moment the phovea_server returns only the data for the given attribute ID, which can be formatted as JSON, CSV or image. 

Here some dimensions for the example above:
* *mRNA*: 12042 rows x 538 cols
* *mRNA-seq*: 18214 rows x 153 cols
* *RPPA*: 171 rows x 214 cols

## What we want

We need all IDs of the largest attribute ID (here *mRNA-seq* with 18214) and "fill up" this with the requested attribute so that we get a sparse matrix.

## Proposals

@sgratzl In following I summarized my thoughts and questions so far. I would I like to know your opinion, which one I should follow, because I don't know all consequences. 

### Extend the server-side

* Extend the dataset API with a flag to include null values
  * General question: Should that work only in row or also column direction?
* Retrieve the largest matrix
  * Check by row/coltype to match only matrices with same idtype
  * Should we also check vectors with the same idtype? Because they might have a different size.
* Will this solution work with the selection mechanism in the frontend?
  * Is it enough to extend the `'/' + type + '/<dataset_id>/data'` route or should `'/' + type + '/<dataset_id>/rowIds'` also return the null value row ids?

### Extend the client-side

For mothertable I could also work on a client-side only solution, since I can retrieve the largest available dimension from the added columns.

* Implement the "fill up" directly in the heatmap
   * How to pass the reference to fill up the missing values?
* How to slice and patch the image texture?
* How to make this work with different renderers (SVG, Canvas)?
* Do we need the "fill up" also for vectors/strings etc?

**Comment by sgratzl** [comment]
> Extend the dataset API with a flag to include null values

there is currently no way to return "no data" or introduce missing values artificially

> Retrieve the largest matrix

the size is not important but the union of all `ids` in the visualized tables

**Comment by sgratzl** [comment]
> Implement the "fill up" directly in the heatmap

you could split up the heatmap in multiple heatmaps and move space between them

**Comment by mstreit** [comment]
I've talked to @sgratzl about possible ways to handle this. There is no easy solution unfortunately. One option is to address the issue temporarily by creating the union of the input tables in python and then load the derived data vectors and matrices.
