### ISSUE TITLE
Hierarchical sort number is wrong during drag operations

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#193]
Let's assume I have three filter elements. If I dragt the third one to become the new second element, it will show 4 during the drag operation (and not 2).

![image](https://cloud.githubusercontent.com/assets/4129755/23659502/a34aeebe-0346-11e7-87e3-2e2f5dd8b9fa.png)

**Comment by thinkh** [comment]
I created the numbers using a CSS counter. Since the jQuery UI draggable creates a new Element while dragging CSS finds 4 elements and updates the order. There is no easy way to change this unless we maintain the numbering in JS (and not CSS) or tell jQuery UI draggable to avoid the element.

In my opinion it's not that severe and we should postpone a fix.

**Comment by mstreit** [comment]
OK.

**Comment by thinkh** [comment]
That was easier than I expected. :) I just excluded the placeholder element from the counter incrementation.
